### ISSUE TITLE
This extension is not installable on any currently installed products

### ISSUE THREAD

**Issue by hickford** [hmemcpy/AnyScriptCs#1]
I tried installing version 0.1.0 from https://visualstudiogallery.msdn.microsoft.com/9600779f-ee03-4b1b-9dfa-5bb9af85085b on Visual Studio 2015 Update 2 but got an error message (log attached)

> This extension is not installable on any currently installed products

Any ideas?

[VSIXInstaller_955ae021-e401-4217-9306-420d5a6e7fbe.txt](https://github.com/hmemcpy/AnyScriptCs/files/250582/VSIXInstaller_955ae021-e401-4217-9306-420d5a6e7fbe.txt)

**Comment by hmemcpy** [comment]
This extension can only be installed in [Visual Studio "15"](https://www.visualstudio.com/en-us/downloads/visual-studio-next-downloads-vs.aspx), the newly announced Visual Studio vNext, and not 2015 (I can see how this is confusing...).
It depends on functionality added in VS "15" (the "Open Folder" feature) which doesn't exist in earlier Visual Studios...

That's why you're getting this message. Sorry!

**Comment by hickford** [comment]
That is confusing! Thanks
